from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter
from pydantic import BaseModel, Field

from services.knowledge_base.chroma_adapter import ChromaKnowledgeBase

router = APIRouter()
_kb = ChromaKnowledgeBase()


class KnowledgeBaseHealthResponse(BaseModel):
    """Phase 1 health spec for the knowledge base service."""

    indexed_tasks: int = Field(..., description="Number of tasks/documents indexed in Chroma")
    storage_status: str = Field(
        ...,
        description="One of: healthy | degraded | unavailable",
    )
    last_ingestion: Optional[str] = Field(
        None,
        description="ISO-8601 timestamp of the last ingestion run, if known",
    )


def _determine_storage_status(healthy: bool, count: int) -> str:
    if not healthy:
        return "unavailable"
    if count == 0:
        return "degraded"
    return "healthy"


def _last_ingestion_from_metadata() -> Optional[str]:
    """Attempt to extract last_ingestion from collection metadata or config.json."""
    meta = _kb.get_collection_metadata()
    ts = meta.get("last_ingestion")
    if ts:
        return str(ts)

    # Fallback: read config.json generated by build_index.py
    try:
        import json
        from pathlib import Path

        db_path = Path(str(_kb.vector_db_path))
        config_path = db_path / "config.json"
        if config_path.is_file():
            with open(config_path, "r", encoding="utf-8") as f:
                cfg = json.load(f)
            ts2 = cfg.get("last_ingestion") or cfg.get("built_at")
            if ts2:
                return str(ts2)
    except Exception:
        pass
    return None


@router.get("/health", response_model=KnowledgeBaseHealthResponse, tags=["knowledge_base"])
def health_check() -> KnowledgeBaseHealthResponse:
    healthy = _kb.is_healthy()
    count = _kb.get_document_count()
    status = _determine_storage_status(healthy, count)
    last_ingestion = _last_ingestion_from_metadata()

    return KnowledgeBaseHealthResponse(
        indexed_tasks=count,
        storage_status=status,
        last_ingestion=last_ingestion,
    )
